import { ISecao } from "@/contextos/ContextoCompra";

const dispensa: ISecao[] = [
    {
        id: 1,
        nome: "Bazar",
        data: [
            { id: 9, nome: "Filtro de papel", qtdDispensa: 0, qtdLista: 0 },
            { id: 7, nome: "Guardanapo", qtdDispensa: 0, qtdLista: 0 },
            { id: 12, nome: "Palitos", qtdDispensa: 0, qtdLista: 0 },            
            { id: 8, nome: "Papel toalha", qtdDispensa: 0, qtdLista: 0 },            
        ]
    },
    {
        id: 2,
        nome: "Bebidas",
        data: [
            { id: 16, nome: "Água com gás", qtdDispensa: 0, qtdLista: 0 },
            { id: 17, nome: "Água de côco", qtdDispensa: 0, qtdLista: 0 },
            { id: 19, nome: "Cerveja", qtdDispensa: 0, qtdLista: 0 },
            { id: 22, nome: "Gelo", qtdDispensa: 0, qtdLista: 0 },
            { id: 24, nome: "Isotônico", qtdDispensa: 0, qtdLista: 0 },
            { id: 26, nome: "Suco de uva integral", qtdDispensa: 0, qtdLista: 0 },            
            { id: 28, nome: "Vinho", qtdDispensa: 0, qtdLista: 0 },
        ]
    },
    {
        id: 3,
        nome: "Carnes",
        data: [
            { id: 31, nome: "Bacalhau", qtdDispensa: 0, qtdLista: 0 },
            { id: 33, nome: "Bacon", qtdDispensa: 0, qtdLista: 0 },   
            { id: 35, nome: "Bisteca suína", qtdDispensa: 0, qtdLista: 0 },
            { id: 36, nome: "Camarão", qtdDispensa: 0, qtdLista: 0 },
            { id: 37, nome: "Carne do sol", qtdDispensa: 0, qtdLista: 0 },
            { id: 38, nome: "Carne moída", qtdDispensa: 0, qtdLista: 0 },
            { id: 29, nome: "Carne para bife", qtdDispensa: 0, qtdLista: 0 },
            { id: 49, nome: "Carne para churrasco", qtdDispensa: 0, qtdLista: 0 },
            { id: 39, nome: "Carne para sopa", qtdDispensa: 0, qtdLista: 0 },
            { id: 40, nome: "Charque", qtdDispensa: 0, qtdLista: 0 },
            { id: 41, nome: "Coração", qtdDispensa: 0, qtdLista: 0 },
            { id: 42, nome: "Costela suína", qtdDispensa: 0, qtdLista: 0 },
            { id: 43, nome: "Coxa de frango", qtdDispensa: 0, qtdLista: 0 },
            { id: 44, nome: "Coxa e sobrecoxa", qtdDispensa: 0, qtdLista: 0 },
            { id: 46, nome: "Fígado", qtdDispensa: 0, qtdLista: 0 },
            { id: 47, nome: "Filé de peito de frango", qtdDispensa: 0, qtdLista: 0 },
            { id: 50, nome: "Frango", qtdDispensa: 0, qtdLista: 0 },
            { id: 51, nome: "Galinha velha", qtdDispensa: 0, qtdLista: 0 },
            { id: 54, nome: "Lombo suíno", qtdDispensa: 0, qtdLista: 0 },
            { id: 58, nome: "Peito de frango", qtdDispensa: 0, qtdLista: 0 },
            { id: 59, nome: "Peixe", qtdDispensa: 0, qtdLista: 0 },
            { id: 60, nome: "Pernil suíno", qtdDispensa: 0, qtdLista: 0 },
            { id: 61, nome: "Peru", qtdDispensa: 0, qtdLista: 0 },
            { id: 64, nome: "Sobrecoxa", qtdDispensa: 0, qtdLista: 0 },
        ]
    },
    {
        id: 4,
        nome: "Frios e Laticínios",
        data: [
            { id: 66, nome: "Achocolatado", qtdDispensa: 0, qtdLista: 0 },   
            { id: 67, nome: "Batata pré-frita", qtdDispensa: 0, qtdLista: 0 },
            { id: 68, nome: "Bebida proteica", qtdDispensa: 0, qtdLista: 0 },   
            { id: 69, nome: "Creme de ricota", qtdDispensa: 0, qtdLista: 0 },
            { id: 70, nome: "Iogurte copinho", qtdDispensa: 0, qtdLista: 0 },
            { id: 71, nome: "Iogurte garrafa", qtdDispensa: 0, qtdLista: 0 },
            { id: 72, nome: "Iogurte garrafinha", qtdDispensa: 0, qtdLista: 0 },
            { id: 73, nome: "Iogurte grego", qtdDispensa: 0, qtdLista: 0 },
            { id: 75, nome: "Leite em pó desnatado", qtdDispensa: 0, qtdLista: 0 },   
            { id: 76, nome: "Leite em pó integral", qtdDispensa: 0, qtdLista: 0 },   
            { id: 77, nome: "Leite fermentado", qtdDispensa: 0, qtdLista: 0 },   
            { id: 78, nome: "Leite líquido desnatado", qtdDispensa: 0, qtdLista: 0 },   
            { id: 79, nome: "Leite líquido integral", qtdDispensa: 0, qtdLista: 0 },   
            { id: 80, nome: "Linguiça", qtdDispensa: 0, qtdLista: 0 },   
            { id: 81, nome: "Manteiga", qtdDispensa: 0, qtdLista: 0 },   
            { id: 82, nome: "Margarina", qtdDispensa: 0, qtdLista: 0 },   
            { id: 83, nome: "Mortadela", qtdDispensa: 0, qtdLista: 0 },   
            { id: 84, nome: "Pão de alho", qtdDispensa: 0, qtdLista: 0 },
            { id: 85, nome: "Pão de queijo", qtdDispensa: 0, qtdLista: 0 },
            { id: 86, nome: "Peito de peru", qtdDispensa: 0, qtdLista: 0 },   
            { id: 87, nome: "Polpa de fruta", qtdDispensa: 0, qtdLista: 0 },
            { id: 88, nome: "Presunto", qtdDispensa: 0, qtdLista: 0 },   
            { id: 89, nome: "Queijo coalho", qtdDispensa: 0, qtdLista: 0 },
            { id: 90, nome: "Queijo do reino", qtdDispensa: 0, qtdLista: 0 },
            { id: 91, nome: "Queijo gorgonzola", qtdDispensa: 0, qtdLista: 0 },
            { id: 92, nome: "Queijo manteiga", qtdDispensa: 0, qtdLista: 0 },
            { id: 93, nome: "Queijo mussarela", qtdDispensa: 0, qtdLista: 0 },
            { id: 94, nome: "Queijo parmesão", qtdDispensa: 0, qtdLista: 0 },
            { id: 95, nome: "Queijo prato", qtdDispensa: 0, qtdLista: 0 },
            { id: 96, nome: "Queijo provolone", qtdDispensa: 0, qtdLista: 0 },
            { id: 97, nome: "Queijo ricota", qtdDispensa: 0, qtdLista: 0 },
            { id: 98, nome: "Requeijão", qtdDispensa: 0, qtdLista: 0 },   
            { id: 99, nome: "Salame", qtdDispensa: 0, qtdLista: 0 },   
            { id: 100, nome: "Salsicha", qtdDispensa: 0, qtdLista: 0 },   
        ]
    },
    {
        id: 5,
        nome: "Higiene e Perfumaria",
        data: [
            { id: 101, nome: "Absorvente", qtdDispensa: 0, qtdLista: 0 },
            { id: 102, nome: "Algodão", qtdDispensa: 0, qtdLista: 0 },
            { id: 104, nome: "Condicionador", qtdDispensa: 0, qtdLista: 0 },
            { id: 105, nome: "Creme dental", qtdDispensa: 0, qtdLista: 0 },
            { id: 106, nome: "Creme para barbear", qtdDispensa: 0, qtdLista: 0 },
            { id: 107, nome: "Creme para pentear", qtdDispensa: 0, qtdLista: 0 },
            { id: 108, nome: "Desodorante", qtdDispensa: 0, qtdLista: 0 },
            { id: 109, nome: "Escova dental", qtdDispensa: 0, qtdLista: 0 },
            { id: 110, nome: "Esmalte", qtdDispensa: 0, qtdLista: 0 },
            { id: 111, nome: "Fio dental", qtdDispensa: 0, qtdLista: 0 },
            { id: 112, nome: "Hastes flexíveis", qtdDispensa: 0, qtdLista: 0 },
            { id: 113, nome: "Hidratante", qtdDispensa: 0, qtdLista: 0 },
            { id: 114, nome: "Lâminas para barbear", qtdDispensa: 0, qtdLista: 0 },
            { id: 115, nome: "Lixa de unhas", qtdDispensa: 0, qtdLista: 0 },
            { id: 116, nome: "Papel higiênico", qtdDispensa: 0, qtdLista: 0 },
            { id: 117, nome: "Protetor solar", qtdDispensa: 0, qtdLista: 0 },
            { id: 118, nome: "Removedor de esmalte", qtdDispensa: 0, qtdLista: 0 },
            { id: 119, nome: "Repelente", qtdDispensa: 0, qtdLista: 0 },
            { id: 120, nome: "Sabonete", qtdDispensa: 0, qtdLista: 0 },
            { id: 121, nome: "Sabonete líquido", qtdDispensa: 0, qtdLista: 0 },
            { id: 122, nome: "Shampoo", qtdDispensa: 0, qtdLista: 0 },
            { id: 123, nome: "Tinta para cabelo", qtdDispensa: 0, qtdLista: 0 },
        ]
    },
    {
        id: 6,
        nome: "Hortifruti e Grangeiro",
        data: [
            { id: 124, nome: "Abacate", qtdDispensa: 0, qtdLista: 0 },
            { id: 125, nome: "Abacaxi", qtdDispensa: 0, qtdLista: 0 },
            { id: 126, nome: "Abóbora", qtdDispensa: 0, qtdLista: 0 },
            { id: 127, nome: "Acerola", qtdDispensa: 0, qtdLista: 0 },
            { id: 128, nome: "Alface", qtdDispensa: 0, qtdLista: 0 },
            { id: 129, nome: "Alho", qtdDispensa: 0, qtdLista: 0 },
            { id: 130, nome: "Ameixa", qtdDispensa: 0, qtdLista: 0 },
            { id: 131, nome: "Ameixa seca", qtdDispensa: 0, qtdLista: 0 },
            { id: 132, nome: "Banana comprida", qtdDispensa: 0, qtdLista: 0 },
            { id: 133, nome: "Banana prata", qtdDispensa: 0, qtdLista: 0 },
            { id: 134, nome: "Batata doce", qtdDispensa: 0, qtdLista: 0 },
            { id: 135, nome: "Batata inglesa", qtdDispensa: 0, qtdLista: 0 },
            { id: 136, nome: "Brócolis", qtdDispensa: 0, qtdLista: 0 },
            { id: 137, nome: "Caju", qtdDispensa: 0, qtdLista: 0 },
            { id: 138, nome: "Cebola", qtdDispensa: 0, qtdLista: 0 },
            { id: 139, nome: "Cenoura", qtdDispensa: 0, qtdLista: 0 },
            { id: 140, nome: "Côco", qtdDispensa: 0, qtdLista: 0 },
            { id: 141, nome: "Côco ralado", qtdDispensa: 0, qtdLista: 0 },
            { id: 142, nome: "Coentro", qtdDispensa: 0, qtdLista: 0 },
            { id: 143, nome: "Couve", qtdDispensa: 0, qtdLista: 0 },
            { id: 144, nome: "Feijão verde", qtdDispensa: 0, qtdLista: 0 },
            { id: 145, nome: "Goiaba", qtdDispensa: 0, qtdLista: 0 },
            { id: 146, nome: "Inhame", qtdDispensa: 0, qtdLista: 0 },
            { id: 147, nome: "Laranja lima", qtdDispensa: 0, qtdLista: 0 },
            { id: 148, nome: "Laranja pera", qtdDispensa: 0, qtdLista: 0 },
            { id: 149, nome: "Limão", qtdDispensa: 0, qtdLista: 0 },
            { id: 150, nome: "Maçã", qtdDispensa: 0, qtdLista: 0 },
            { id: 151, nome: "Macaxeira", qtdDispensa: 0, qtdLista: 0 },
            { id: 152, nome: "Mamão", qtdDispensa: 0, qtdLista: 0 },
            { id: 153, nome: "Manga", qtdDispensa: 0, qtdLista: 0 },
            { id: 154, nome: "Maracujá", qtdDispensa: 0, qtdLista: 0 },
            { id: 155, nome: "Melancia", qtdDispensa: 0, qtdLista: 0 },
            { id: 156, nome: "Melão", qtdDispensa: 0, qtdLista: 0 },
            { id: 157, nome: "Milho", qtdDispensa: 0, qtdLista: 0 },
            { id: 158, nome: "Morango", qtdDispensa: 0, qtdLista: 0 },
            { id: 159, nome: "Pera", qtdDispensa: 0, qtdLista: 0 },
            { id: 160, nome: "Pimentão", qtdDispensa: 0, qtdLista: 0 },
            { id: 161, nome: "Quiabo", qtdDispensa: 0, qtdLista: 0 },
            { id: 162, nome: "Tomate", qtdDispensa: 0, qtdLista: 0 },
            { id: 163, nome: "Uva", qtdDispensa: 0, qtdLista: 0 },
            { id: 164, nome: "Uva passa", qtdDispensa: 0, qtdLista: 0 },
        ]
    },
    {
        id: 7,
        nome: "Limpeza",
        data: [
            { id: 165, nome: "Água sanitária", qtdDispensa: 0, qtdLista: 0 },
            { id: 166, nome: "Amaciante", qtdDispensa: 0, qtdLista: 0 },
            { id: 167, nome: "Antimofo", qtdDispensa: 0, qtdLista: 0 },
            { id: 168, nome: "Cera líquida para móveis", qtdDispensa: 0, qtdLista: 0 },
            { id: 169, nome: "Corda para varal", qtdDispensa: 0, qtdLista: 0 },
            { id: 170, nome: "Desengordurante", qtdDispensa: 0, qtdLista: 0 },
            { id: 173, nome: "Desinfetante", qtdDispensa: 0, qtdLista: 0 },
            { id: 174, nome: "Detergente", qtdDispensa: 0, qtdLista: 0 },
            { id: 171, nome: "Esponja", qtdDispensa: 0, qtdLista: 0 },
            { id: 172, nome: "Fósforo", qtdDispensa: 0, qtdLista: 0 },
            { id: 175, nome: "Lã de aço", qtdDispensa: 0, qtdLista: 0 },
            { id: 176, nome: "Lava roupas líquido", qtdDispensa: 0, qtdLista: 0 },
            { id: 177, nome: "Limpa piso", qtdDispensa: 0, qtdLista: 0 },
            { id: 178, nome: "Limpa vidro", qtdDispensa: 0, qtdLista: 0 },
            { id: 15, nome: "Limpador perfumado", qtdDispensa: 0, qtdLista: 0 },
            { id: 179, nome: "Luva", qtdDispensa: 0, qtdLista: 0 },
            { id: 180, nome: "Óleo de peroba", qtdDispensa: 0, qtdLista: 0 },
            { id: 181, nome: "Pá", qtdDispensa: 0, qtdLista: 0 },
            { id: 182, nome: "Pano de chão", qtdDispensa: 0, qtdLista: 0 },
            { id: 183, nome: "Pano multiuso", qtdDispensa: 0, qtdLista: 0 },
            { id: 184, nome: "Prendedor de roupa", qtdDispensa: 0, qtdLista: 0 },
            { id: 185, nome: "Rodo", qtdDispensa: 0, qtdLista: 0 },
            { id: 186, nome: "Sabão em barra", qtdDispensa: 0, qtdLista: 0 },
            { id: 187, nome: "Sabão em pó", qtdDispensa: 0, qtdLista: 0 },
            { id: 188, nome: "Saco para lixo", qtdDispensa: 0, qtdLista: 0 },
            { id: 189, nome: "Tira manchas", qtdDispensa: 0, qtdLista: 0 },
            { id: 190, nome: "Vassoura", qtdDispensa: 0, qtdLista: 0 },
        ]
    },
    {
        id: 8,
        nome: "Mercearia",
        data: [
            { id: 191, nome: "Achocolatado em pó", qtdDispensa: 0, qtdLista: 0 },
            { id: 192, nome: "Açúcar cristal", qtdDispensa: 0, qtdLista: 0 },
            { id: 193, nome: "Açúcar demerara", qtdDispensa: 0, qtdLista: 0 },
            { id: 194, nome: "Açúcar mascavo", qtdDispensa: 0, qtdLista: 0 },
            { id: 10, nome: "Adoçante", qtdDispensa: 0, qtdLista: 0 },
            { id: 195, nome: "Amendoim", qtdDispensa: 0, qtdLista: 0 },
            { id: 196, nome: "Amido de milho", qtdDispensa: 0, qtdLista: 0 },
            { id: 197, nome: "Arroz branco", qtdDispensa: 0, qtdLista: 0 },
            { id: 198, nome: "Arroz da terra", qtdDispensa: 0, qtdLista: 0 },
            { id: 199, nome: "Arroz integral", qtdDispensa: 0, qtdLista: 0 },
            { id: 200, nome: "Arroz parboilizado", qtdDispensa: 0, qtdLista: 0 },
            { id: 201, nome: "Atum ralado", qtdDispensa: 0, qtdLista: 0 },
            { id: 202, nome: "Atum sólido", qtdDispensa: 0, qtdLista: 0 },
            { id: 203, nome: "Aveia em flocos finos", qtdDispensa: 0, qtdLista: 0 },
            { id: 204, nome: "Aveia em flocos grossos", qtdDispensa: 0, qtdLista: 0 },
            { id: 205, nome: "Azeite", qtdDispensa: 0, qtdLista: 0 },
            { id: 206, nome: "Azeitona", qtdDispensa: 0, qtdLista: 0 },
            { id: 207, nome: "Azeitona sem caroço", qtdDispensa: 0, qtdLista: 0 },
            { id: 208, nome: "Bananola", qtdDispensa: 0, qtdLista: 0 },   
            { id: 209, nome: "Barra de cereal", qtdDispensa: 0, qtdLista: 0 },
            { id: 210, nome: "Barra de proteína", qtdDispensa: 0, qtdLista: 0 },
            { id: 211, nome: "Biscoito água", qtdDispensa: 0, qtdLista: 0 },
            { id: 212, nome: "Biscoito água com gergelim", qtdDispensa: 0, qtdLista: 0 },
            { id: 213, nome: "Biscoito amanteigado", qtdDispensa: 0, qtdLista: 0 },
            { id: 214, nome: "Biscoito Club Social", qtdDispensa: 0, qtdLista: 0 },
            { id: 215, nome: "Biscoito cookie", qtdDispensa: 0, qtdLista: 0 },
            { id: 216, nome: "Biscoito coquinho", qtdDispensa: 0, qtdLista: 0 },
            { id: 217, nome: "Biscoito cream cracker", qtdDispensa: 0, qtdLista: 0 },
            { id: 218, nome: "Biscoito de leite com gotas de chocolate", qtdDispensa: 0, qtdLista: 0 },
            { id: 219, nome: "Biscoito goiabinha", qtdDispensa: 0, qtdLista: 0 },
            { id: 220, nome: "Biscoito lanche", qtdDispensa: 0, qtdLista: 0 },
            { id: 221, nome: "Biscoito maizena", qtdDispensa: 0, qtdLista: 0 },
            { id: 222, nome: "Biscoito maria", qtdDispensa: 0, qtdLista: 0 },
            { id: 223, nome: "Biscoito Passatempo de leite", qtdDispensa: 0, qtdLista: 0 },
            { id: 224, nome: "Biscoito Passatempo recheado", qtdDispensa: 0, qtdLista: 0 },
            { id: 225, nome: "Biscoito recheado", qtdDispensa: 0, qtdLista: 0 },
            { id: 226, nome: "Biscoito tortinha", qtdDispensa: 0, qtdLista: 0 },
            { id: 227, nome: "Biscoito wafer", qtdDispensa: 0, qtdLista: 0 },
            { id: 228, nome: "Café em capsula", qtdDispensa: 0, qtdLista: 0 },
            { id: 229, nome: "Café solúvel", qtdDispensa: 0, qtdLista: 0 },
            { id: 230, nome: "Café torrado em grãos", qtdDispensa: 0, qtdLista: 0 },
            { id: 231, nome: "Café torrado moído", qtdDispensa: 0, qtdLista: 0 },
            { id: 232, nome: "Canela", qtdDispensa: 0, qtdLista: 0 },   
            { id: 233, nome: "Canela em pó", qtdDispensa: 0, qtdLista: 0 },   
            { id: 234, nome: "Capuccino", qtdDispensa: 0, qtdLista: 0 },
            { id: 235, nome: "Carvão", qtdDispensa: 0, qtdLista: 0 },
            { id: 236, nome: "Catchup", qtdDispensa: 0, qtdLista: 0 },
            { id: 237, nome: "Cereal matinal", qtdDispensa: 0, qtdLista: 0 },
            { id: 238, nome: "Chocolate em barra", qtdDispensa: 0, qtdLista: 0 },
            { id: 239, nome: "Chocolate em pó", qtdDispensa: 0, qtdLista: 0 },
            { id: 240, nome: "Cravo da Índia", qtdDispensa: 0, qtdLista: 0 },
            { id: 241, nome: "Creme de leite", qtdDispensa: 0, qtdLista: 0 },
            { id: 242, nome: "Cuscuz", qtdDispensa: 0, qtdLista: 0 },
            { id: 243, nome: "Doce de leite", qtdDispensa: 0, qtdLista: 0 },      
            { id: 244, nome: "Ervilha em conserva", qtdDispensa: 0, qtdLista: 0 },
            { id: 245, nome: "Extrato de tomate", qtdDispensa: 0, qtdLista: 0 },
            { id: 246, nome: "Farelo de aveia", qtdDispensa: 0, qtdLista: 0 },
            { id: 247, nome: "Farinha de aveia", qtdDispensa: 0, qtdLista: 0 },
            { id: 248, nome: "Farinha de mandioca", qtdDispensa: 0, qtdLista: 0 },
            { id: 249, nome: "Farinha de mandioca com açafrão", qtdDispensa: 0, qtdLista: 0 },
            { id: 250, nome: "Farinha de rosca", qtdDispensa: 0, qtdLista: 0 },
            { id: 251, nome: "Farinha de trigo", qtdDispensa: 0, qtdLista: 0 },
            { id: 252, nome: "Farinha láctea", qtdDispensa: 0, qtdLista: 0 },
            { id: 253, nome: "Farofa", qtdDispensa: 0, qtdLista: 0 },
            { id: 254, nome: "Feijão carioca", qtdDispensa: 0, qtdLista: 0 },
            { id: 255, nome: "Feijão preto", qtdDispensa: 0, qtdLista: 0 },
            { id: 256, nome: "Fermento biológico", qtdDispensa: 0, qtdLista: 0 },
            { id: 257, nome: "Fermento químico em pó", qtdDispensa: 0, qtdLista: 0 },
            { id: 258, nome: "Gelatina", qtdDispensa: 0, qtdLista: 0 },   
            { id: 259, nome: "Geleia", qtdDispensa: 0, qtdLista: 0 },   
            { id: 260, nome: "Goiabada", qtdDispensa: 0, qtdLista: 0 },   
            { id: 261, nome: "Goma para tapioca", qtdDispensa: 0, qtdLista: 0 },
            { id: 262, nome: "Grão de bico", qtdDispensa: 0, qtdLista: 0 },
            { id: 263, nome: "Leite condensado", qtdDispensa: 0, qtdLista: 0 },
            { id: 264, nome: "Leite de côco", qtdDispensa: 0, qtdLista: 0 },
            { id: 265, nome: "Macarrão espaguete", qtdDispensa: 0, qtdLista: 0 },
            { id: 266, nome: "Macarrão ninho", qtdDispensa: 0, qtdLista: 0 },
            { id: 267, nome: "Macarrão parafuso", qtdDispensa: 0, qtdLista: 0 },
            { id: 268, nome: "Maionese", qtdDispensa: 0, qtdLista: 0 },
            { id: 269, nome: "Massa para lasanha", qtdDispensa: 0, qtdLista: 0 },
            { id: 270, nome: "Milho para munguzá", qtdDispensa: 0, qtdLista: 0 },
            { id: 271, nome: "Milho para pipoca", qtdDispensa: 0, qtdLista: 0 },
            { id: 272, nome: "Milho verde em conserva", qtdDispensa: 0, qtdLista: 0 },
            { id: 273, nome: "Molho de tomate", qtdDispensa: 0, qtdLista: 0 },    
            { id: 274, nome: "Mostarda", qtdDispensa: 0, qtdLista: 0 },
            { id: 275, nome: "Nutella", qtdDispensa: 0, qtdLista: 0 },
            { id: 276, nome: "Óleo", qtdDispensa: 0, qtdLista: 0 },
            { id: 277, nome: "Paçoca", qtdDispensa: 0, qtdLista: 0 },   
            { id: 278, nome: "Palmito", qtdDispensa: 0, qtdLista: 0 },
            { id: 279, nome: "Patê de atum", qtdDispensa: 0, qtdLista: 0 },
            { id: 280, nome: "Penne", qtdDispensa: 0, qtdLista: 0 },
            { id: 281, nome: "Polvilho azedo", qtdDispensa: 0, qtdLista: 0 },
            { id: 282, nome: "Queijo ralado", qtdDispensa: 0, qtdLista: 0 },
            { id: 283, nome: "Rosquinha", qtdDispensa: 0, qtdLista: 0 },
            { id: 284, nome: "Sal", qtdDispensa: 0, qtdLista: 0 },
            { id: 285, nome: "Sal grosso", qtdDispensa: 0, qtdLista: 0 },
            { id: 286, nome: "Sardinha enlatada", qtdDispensa: 0, qtdLista: 0 },
            { id: 287, nome: "Tempero Açafrão", qtdDispensa: 0, qtdLista: 0 },
            { id: 288, nome: "Tempero Curry", qtdDispensa: 0, qtdLista: 0 },
            { id: 289, nome: "Tempero Oregano", qtdDispensa: 0, qtdLista: 0 },
            { id: 290, nome: "Torrada", qtdDispensa: 0, qtdLista: 0 },
            { id: 291, nome: "Vinagre", qtdDispensa: 0, qtdLista: 0 },
            { id: 292, nome: "Xerém", qtdDispensa: 0, qtdLista: 0 },
        ]
    },
    {
        id: 9,
        nome: "Padaria",
        data: [
            { id: 293, nome: "Bolacha folheada doce", qtdDispensa: 0, qtdLista: 0 },
            { id: 294, nome: "Bolacha Jucurutu", qtdDispensa: 0, qtdLista: 0 },
            { id: 295, nome: "Bolacha sete capas", qtdDispensa: 0, qtdLista: 0 },
            { id: 296, nome: "Bolo", qtdDispensa: 0, qtdLista: 0 },
            { id: 297, nome: "Pão bisnaguinha", qtdDispensa: 0, qtdLista: 0 },
            { id: 298, nome: "Pão de cachorro quente", qtdDispensa: 0, qtdLista: 0 },
            { id: 299, nome: "Pão de forma", qtdDispensa: 0, qtdLista: 0 },
            { id: 300, nome: "Pão de forma integral", qtdDispensa: 0, qtdLista: 0 },
            { id: 301, nome: "Pão de hamburguer", qtdDispensa: 0, qtdLista: 0 },
            { id: 302, nome: "Pão doce", qtdDispensa: 0, qtdLista: 0 },
            { id: 303, nome: "Pão francês", qtdDispensa: 0, qtdLista: 0 },
            { id: 304, nome: "Pão seda", qtdDispensa: 0, qtdLista: 0 },
            { id: 305, nome: "Tareco", qtdDispensa: 0, qtdLista: 0 },
        ]
    },
];

export default dispensa;